"""
Django settings for modalite project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-av8tgjmuk5=ehmq*qm9*euzku(@absw4*351u%x$ry^wbiei3c"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    'django_extensions',
    "imagerie",
    #'bootstrap5',
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "modalite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "modalite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db2.sqlite3",
    },
    "olddb": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path("/home/kligliro/repos_modalite/modalite/db.sqlite3"),
    },
    #"modalite": {        
    #    "ENGINE": "django.db.backends.mysql",
    #    "NAME": "modalite",
    #    "USER": "kligliro",
    #    "PASSWORD": "%LokO80%",
    #    "PORT": 3306,
    #},

    # "modalite": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "/home/kligliro/repos_modalite_bio/modalite_bio/db.sqlite3",
    # },
    # "modalmysql": {
    #     "ENGINE": "django.db.backends.mysql",
    #     'OPTIONS': {
    #     	'read_default_file': BASE_DIR / 'repos_modalite/my.cnf',
    # 	}, 
    # },
    #"mymodal": {
    #    "NAME": "modalite",
    #    "ENGINE": "django.db.backends.mysql",
    #    "USER": "kligliro",
    #    "PASSWORD": "%LokO80%",
    #},
    # "modalmysql": {
    #     "ENGINE": "django.db.backends.mysql",
    #     'NAME': "modalite",  
    #     'USER': "kligliro",  
    #     'PASSWORD': "%LokO80%",  
    #     # 'HOST': "172.19.23.10",
    #     'HOST': "127.0.0.1",
    #     'PORT': "3306",  
    # },
}

# print("utilisation de la BDD <olddb> accessible ici : /home/kligliro/repos_modalite/modalite/db.sqlite3 ")

# AUTH_USER_MODEL = 'imagerie.MUser'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# o.dhcp=0 if o.dhcp else 1

"""
OLD : Modalite :         OLD : Net :        OLD : Vlan :        NEW : Modalite :
id                      id                  id                  id
aet                     addrip              num                 aet
port                    hostname            nom                 port
pacs_id                 macaddr             divers              service_id
service_id              mask                                    appareil_id                            
worklist_id             gw                                      appareiltype_id
appareil_id             dns1                                    loc_id
appareiltype_id         dns2                                    addrip
loc_id                  dhcp                                    dhcp
net_id                  vlan_id                                 dns1
                                                                dns2
                                                                gw
                                                                hostname
                                                                macaddr
                                                                mask
                                                                vlan_id
                                                                serveur
                                                                pacs_id
                                                                worklist_id
"""

