# Generated by Django 4.0 on 2024-11-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0003_alter_modalite_net_alter_pacs_net_alter_printer_net_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacs',
            name='net',
            field=models.ForeignKey(blank=True, help_text=' Réseau ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='net_pacs', to='imagerie.net'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='net',
            field=models.ForeignKey(blank=True, help_text=' Réseau ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='net_printer', to='imagerie.net'),
        ),
        migrations.AlterField(
            model_name='store',
            name='net',
            field=models.ForeignKey(blank=True, help_text=' Réseau ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='net_store', to='imagerie.net'),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='net',
            field=models.ForeignKey(blank=True, help_text=' Réseau ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='net_worklist', to='imagerie.net'),
        ),
    ]
