# Generated by Django 5.1.3 on 2024-11-13 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0005_localisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modalite",
            name="nom",
        ),
        migrations.AddField(
            model_name="modalite",
            name="appareil",
            field=models.ForeignKey(
                blank=True,
                help_text=" Pacs ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appareil_modalite",
                to="imagerie.appareil",
            ),
        ),
        migrations.AddField(
            model_name="modalite",
            name="appareiltype",
            field=models.ForeignKey(
                blank=True,
                help_text=" Pacs ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appareiltype_modalite",
                to="imagerie.appareiltype",
            ),
        ),
    ]
