# Generated by Django 5.1.3 on 2024-11-13 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0007_modalite_loc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modalite",
            name="net",
            field=models.ForeignKey(
                blank=True,
                help_text=" Réseau ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="net_modalite",
                to="imagerie.net",
            ),
        ),
    ]
