# Generated by Django 5.1.3 on 2024-11-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0008_alter_modalite_net"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modalite",
            name="printer",
            field=models.ManyToManyField(
                blank=True,
                help_text=" différents PRINT où l'on peut imprimer les examens",
                to="imagerie.printer",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="store",
            field=models.ManyToManyField(
                blank=True,
                help_text=" différents STORE où l'on peut pousser les examens",
                to="imagerie.store",
            ),
        ),
    ]
