# Generated by Django 5.1.3 on 2024-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0010_alter_modalite_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modalite",
            name="store",
            field=models.ManyToManyField(
                blank=True,
                help_text=" différents STORE où l'on peut pousser les examens",
                related_name="modalites",
                to="imagerie.store",
            ),
        ),
    ]
