# Generated by Django 5.1.3 on 2024-12-11 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0011_alter_modalite_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modalite",
            name="printer",
        ),
        migrations.RemoveField(
            model_name="modalite",
            name="store",
        ),
        migrations.AddField(
            model_name="modalite",
            name="printers",
            field=models.ManyToManyField(
                blank=True,
                help_text=" différents PRINT où l'on peut imprimer les examens",
                related_name="modalite_printers",
                to="imagerie.printer",
            ),
        ),
        migrations.AddField(
            model_name="modalite",
            name="stores",
            field=models.ManyToManyField(
                blank=True,
                help_text=" différents STORE où l'on peut pousser les examens",
                related_name="modalite_stores",
                to="imagerie.store",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="appareil",
            field=models.ForeignKey(
                blank=True,
                help_text=" Pacs ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_appareil",
                to="imagerie.appareil",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="appareiltype",
            field=models.ForeignKey(
                blank=True,
                help_text=" Pacs ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_appareiltype",
                to="imagerie.appareiltype",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="loc",
            field=models.ForeignKey(
                blank=True,
                help_text=" Localisation ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_loc",
                to="imagerie.localisation",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="net",
            field=models.ForeignKey(
                blank=True,
                help_text=" Réseau ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_net",
                to="imagerie.net",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="pacs",
            field=models.ForeignKey(
                blank=True,
                help_text=" Pacs ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_pacs",
                to="imagerie.pacs",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text=" Service ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_service",
                to="imagerie.service",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="worklist",
            field=models.ForeignKey(
                blank=True,
                help_text=" Worklist ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_worklist",
                to="imagerie.worklist",
            ),
        ),
        migrations.AlterField(
            model_name="net",
            name="vlan",
            field=models.ForeignKey(
                blank=True,
                help_text=" Vlan ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="net_vlan",
                to="imagerie.vlan",
            ),
        ),
        migrations.AlterField(
            model_name="pacs",
            name="net",
            field=models.ForeignKey(
                blank=True,
                help_text=" Réseau ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pacs_net",
                to="imagerie.net",
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="net",
            field=models.ForeignKey(
                blank=True,
                help_text=" Réseau ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printer_net",
                to="imagerie.net",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="net",
            field=models.ForeignKey(
                blank=True,
                help_text=" Réseau ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store_net",
                to="imagerie.net",
            ),
        ),
        migrations.AlterField(
            model_name="worklist",
            name="net",
            field=models.ForeignKey(
                blank=True,
                help_text=" Réseau ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="worklist_net",
                to="imagerie.net",
            ),
        ),
    ]
