# Generated by Django 5.1.3 on 2024-12-12 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0012_remove_modalite_printer_remove_modalite_store_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="net",
            old_name="masq",
            new_name="masK",
        ),
    ]
