# Generated by Django 5.1.3 on 2024-12-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0013_rename_masq_net_mask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="net",
            old_name="masK",
            new_name="mask",
        ),
    ]
