# Generated by Django 5.1 on 2024-12-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0014_rename_mask_net_mask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="net",
            name="vlan",
        ),
        migrations.RemoveField(
            model_name="modalite",
            name="net",
        ),
        migrations.RemoveField(
            model_name="pacs",
            name="net",
        ),
        migrations.RemoveField(
            model_name="worklist",
            name="net",
        ),
        migrations.RemoveField(
            model_name="store",
            name="net",
        ),
        migrations.AlterField(
            model_name="modalite",
            name="pacs",
            field=models.ForeignKey(
                blank=True,
                help_text=" Pacs ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_pacs",
                to="imagerie.modalite",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="worklist",
            field=models.ForeignKey(
                blank=True,
                help_text=" Worklist ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_worklist",
                to="imagerie.modalite",
            ),
        ),
        migrations.AlterModelOptions(
            name="appareil",
            options={"managed": True, "ordering": ["nom"]},
        ),
        migrations.AlterModelOptions(
            name="appareiltype",
            options={"managed": True, "ordering": ["nom"]},
        ),
        migrations.AlterModelOptions(
            name="localisation",
            options={"managed": True, "ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="marque",
            options={"managed": True, "ordering": ["nom"]},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"managed": True, "ordering": ["nom"]},
        ),
        migrations.AlterModelOptions(
            name="vlan",
            options={"managed": True, "ordering": ["nom"]},
        ),
        migrations.AddField(
            model_name="modalite",
            name="addrip",
            field=models.GenericIPAddressField(
                blank=True, default="0.0.0.0", null=True
            ),
        ),
        migrations.AddField(
            model_name="modalite",
            name="dhcp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modalite",
            name="dns1",
            field=models.GenericIPAddressField(
                blank=True, default="10.200.1.10", null=True
            ),
        ),
        migrations.AddField(
            model_name="modalite",
            name="dns2",
            field=models.GenericIPAddressField(
                blank=True, default="172.25.16.10", null=True
            ),
        ),
        migrations.AddField(
            model_name="modalite",
            name="gw",
            field=models.GenericIPAddressField(
                blank=True, default="0.0.0.1", null=True
            ),
        ),
        migrations.AddField(
            model_name="modalite",
            name="hostname",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="modalite",
            name="macaddr",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="modalite",
            name="mask",
            field=models.CharField(
                blank=True, default="255.255.255.0", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="modalite",
            name="vlan",
            field=models.ForeignKey(
                blank=True,
                help_text=" Vlan ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="net_vlan",
                to="imagerie.vlan",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="aet",
            field=models.CharField(
                blank=True, help_text=" Aet ", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="appareil",
            field=models.ForeignKey(
                blank=True,
                help_text=" Appareil ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_appareil",
                to="imagerie.appareil",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="appareiltype",
            field=models.ForeignKey(
                blank=True,
                help_text=" Appareiltype ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_appareiltype",
                to="imagerie.appareiltype",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="printers",
            field=models.ManyToManyField(
                blank=True,
                help_text=" différents PRINT où l'on peut imprimer les examens",
                related_name="modalite_printers",
                to="imagerie.modalite",
            ),
        ),
        migrations.AlterField(
            model_name="modalite",
            name="stores",
            field=models.ManyToManyField(
                blank=True,
                help_text=" différents STORE où l'on peut pousser les examens",
                related_name="modalite_stores",
                to="imagerie.modalite",
            ),
        ),
        migrations.DeleteModel(
            name="Printer",
        ),
        migrations.DeleteModel(
            name="Net",
        ),
        migrations.DeleteModel(
            name="Store",
        ),
        migrations.DeleteModel(
            name="Pacs",
        ),
        migrations.DeleteModel(
            name="Worklist",
        ),
    ]
