# Generated by Django 5.1 on 2024-12-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "imagerie",
            "0015_remove_net_vlan_remove_modalite_net_remove_pacs_net_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="modalite",
            name="serveur",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NA", "N/A"),
                    ("PA", "PACS"),
                    ("WL", "WL"),
                    ("DA", "DACS"),
                    ("ST", "STORE"),
                    ("PR", "PRINT"),
                    ("OT", "OTHER"),
                    ("IN", "INFORM"),
                ],
                default="NA",
                max_length=2,
                null=True,
            ),
        ),
    ]
