# Generated by Django 5.1 on 2025-01-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0016_modalite_serveur"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="modalite",
            constraint=models.UniqueConstraint(
                fields=("addrip", "aet", "port"), name="unique_dicom"
            ),
        ),
    ]
