# Generated by Django 5.1 on 2025-01-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0017_modalite_unique_dicom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modalite",
            name="serveur",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NA", "N/A"),
                    ("PA", "PACS"),
                    ("WL", "WL"),
                    ("DA", "DACS"),
                    ("ST", "STORE"),
                    ("PR", "PRINT"),
                    ("IN", "INFORM"),
                    ("UC", "ORDI"),
                    ("OT", "OTHER"),
                ],
                default="NA",
                max_length=2,
                null=True,
            ),
        ),
    ]
