# Generated by Django 5.1 on 2025-01-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0020_remove_bdd_projet_remove_hard_modedegrade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projet",
            name="hard",
        ),
        migrations.RemoveField(
            model_name="soft",
            name="referent",
        ),
        migrations.AddField(
            model_name="projet",
            name="hards",
            field=models.ManyToManyField(
                blank=True,
                help_text=" matériels achetés, fournis... ",
                related_name="projet_hards",
                to="imagerie.hard",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="softs",
            field=models.ManyToManyField(
                blank=True,
                help_text=" Logiciels achetés, fournis...",
                related_name="projet_softs",
                to="imagerie.soft",
            ),
        ),
    ]
