# Generated by Django 5.1 on 2025-01-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "imagerie",
            "0021_remove_projet_hard_remove_soft_referent_projet_hards_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hard",
            options={"managed": True, "ordering": ["description"]},
        ),
        migrations.RenameField(
            model_name="hard",
            old_name="nom",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="hard",
            name="bdd",
        ),
        migrations.RemoveField(
            model_name="hard",
            name="resspartage",
        ),
        migrations.AlterField(
            model_name="hard",
            name="stype",
            field=models.CharField(
                blank=True,
                choices=[("NA", "N/A"), ("VM", "VM"), ("PHY", "PHYSIQUE")],
                default="VM",
                max_length=3,
                null=True,
            ),
        ),
    ]
