# Generated by Django 5.1 on 2025-01-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0022_alter_hard_options_rename_nom_hard_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdd",
            name="unc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
