# Generated by Django 5.1 on 2025-01-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0023_alter_bdd_unc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hard",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
