# Generated by Django 5.1 on 2025-01-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0024_alter_hard_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soft",
            old_name="os",
            new_name="demande",
        ),
        migrations.AddField(
            model_name="soft",
            name="fournisseur",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="soft",
            name="softs",
            field=models.ManyToManyField(
                blank=True,
                help_text=" différents soft possibles",
                related_name="softs_softs",
                to="imagerie.soft",
            ),
        ),
        migrations.AddField(
            model_name="soft",
            name="softtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NA", "N/A"),
                    ("OS", "Sysyteme d'exploitation"),
                    ("APP", "Logiciel métier"),
                ],
                default="VM",
                max_length=3,
                null=True,
            ),
        ),
    ]
