# Generated by Django 5.1 on 2025-01-03 23:22

import imagerie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "imagerie",
            "0025_rename_os_soft_demande_soft_fournisseur_soft_softs_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soft",
            name="softs",
        ),
        migrations.AddField(
            model_name="soft",
            name="licence",
            field=models.CharField(
                blank=True,
                help_text="max d' info sur celle-ci (n°, clé USB, dongle, flottante,.... ?",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soft",
            name="validité",
            field=models.DateTimeField(
                default=imagerie.models.Soft.one_year_from_today,
                verbose_name="valide jusque...",
            ),
        ),
    ]
