# Generated by Django 5.1 on 2025-01-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0026_remove_soft_softs_soft_licence_soft_validité"),
    ]

    operations = [
        migrations.AddField(
            model_name="connect",
            name="nom",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
