# Generated by Django 5.1 on 2025-01-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0027_connect_nom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modalite",
            name="connect",
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "bdd",
                    models.ForeignKey(
                        blank=True,
                        help_text=" connexion à BDD ",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Connection_bdd",
                        to="imagerie.bdd",
                    ),
                ),
                (
                    "ras",
                    models.ForeignKey(
                        blank=True,
                        help_text=" compte ras_xxx ",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Connection_ras",
                        to="imagerie.ras",
                    ),
                ),
                (
                    "resspartage",
                    models.ForeignKey(
                        blank=True,
                        help_text=" ressource partagée ",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Connection_resspartage",
                        to="imagerie.resspartage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="modalite",
            name="Connection",
            field=models.OneToOneField(
                blank=True,
                help_text=" connnectivité de la machine ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modalite_Connection",
                to="imagerie.connection",
            ),
        ),
        migrations.DeleteModel(
            name="Connect",
        ),
    ]
