# Generated by Django 5.1 on 2025-01-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0028_remove_modalite_connect_connection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdd",
            name="identifiant",
            field=models.ManyToManyField(
                blank=True, help_text=" Identifiant # ", to="imagerie.identifiant"
            ),
        ),
        migrations.AlterField(
            model_name="resspartage",
            name="identifiant",
            field=models.ManyToManyField(
                blank=True, help_text=" Identifiant # ", to="imagerie.identifiant"
            ),
        ),
    ]
