# Generated by Django 5.1 on 2025-01-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0029_alter_bdd_identifiant_alter_resspartage_identifiant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modalite",
            name="soft",
        ),
        migrations.AddField(
            model_name="modalite",
            name="soft",
            field=models.ManyToManyField(
                blank=True,
                help_text=" configuration logicielle de la machine ",
                null=True,
                related_name="modalite_soft",
                to="imagerie.soft",
            ),
        ),
    ]
