# Generated by Django 5.1 on 2025-01-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0030_remove_modalite_soft_modalite_soft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modalite",
            name="soft",
            field=models.ManyToManyField(
                blank=True,
                help_text=" configuration logicielle de la machine ",
                related_name="modalite_soft",
                to="imagerie.soft",
            ),
        ),
    ]
