# Generated by Django 5.1 on 2025-01-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0031_alter_modalite_soft"),
    ]

    operations = [
        migrations.AddField(
            model_name="modalite",
            name="reforme",
            field=models.BooleanField(default=False, help_text=" réformé ? "),
        ),
    ]
