# Generated by Django 5.1.5 on 2025-01-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0032_modalite_reforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalite',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
