# Generated by Django 5.1.5 on 2025-01-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0034_alter_bdd_nom_alter_connection_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalite',
            name='ping',
            field=models.BooleanField(default=False, help_text=' joignable par ping ? '),
        ),
    ]
