# Generated by Django 5.1.5 on 2025-01-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0035_modalite_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalite',
            name='recent_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
