# Generated by Django 5.1.5 on 2025-01-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0036_modalite_recent_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalite',
            name='first_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
