# Generated by Django 5.1.5 on 2025-01-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0037_modalite_first_ping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalite',
            name='first_ping',
        ),
        migrations.RemoveField(
            model_name='modalite',
            name='recent_ping',
        ),
    ]
