# Generated by Django 5.1.5 on 2025-01-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0038_remove_modalite_first_ping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalite',
            name='first_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modalite',
            name='recent_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
