# Generated by Django 5.1.5 on 2025-06-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0040_alter_connection_options_alter_connection_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodalite',
            name='n_invent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalmodalite',
            name='n_system',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modalite',
            name='n_invent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modalite',
            name='n_system',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
