# Generated by Django 5.1.5 on 2025-06-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0042_alter_historicalmodalite_connection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdd',
            options={'managed': True, 'verbose_name_plural': 'bases de données'},
        ),
        migrations.AlterModelOptions(
            name='hard',
            options={'managed': True, 'ordering': ['description'], 'verbose_name_plural': 'Hardwares'},
        ),
        migrations.AlterModelOptions(
            name='historicalbdd',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bdd', 'verbose_name_plural': 'historical bases de données'},
        ),
        migrations.AlterModelOptions(
            name='historicalhard',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical hard', 'verbose_name_plural': 'historical Hardwares'},
        ),
        migrations.AlterModelOptions(
            name='historicalmodalite',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical modalite', 'verbose_name_plural': 'historical Modalités'},
        ),
        migrations.AlterModelOptions(
            name='historicalras',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ras', 'verbose_name_plural': 'historical Comptes Ras'},
        ),
        migrations.AlterModelOptions(
            name='historicalresspartage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resspartage', 'verbose_name_plural': 'historical ressources partagées'},
        ),
        migrations.AlterModelOptions(
            name='historicalsoft',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical soft', 'verbose_name_plural': 'historical Logiciels'},
        ),
        migrations.AlterModelOptions(
            name='modalite',
            options={'managed': True, 'ordering': ['aet'], 'verbose_name_plural': 'Modalités'},
        ),
        migrations.AlterModelOptions(
            name='ras',
            options={'managed': True, 'verbose_name_plural': 'Comptes Ras'},
        ),
        migrations.AlterModelOptions(
            name='resspartage',
            options={'managed': True, 'verbose_name_plural': 'ressources partagées'},
        ),
        migrations.AlterModelOptions(
            name='soft',
            options={'managed': True, 'verbose_name_plural': 'Logiciels'},
        ),
        migrations.RemoveField(
            model_name='historicalmodalite',
            name='ping',
        ),
        migrations.RemoveField(
            model_name='historicalmodalite',
            name='recent_ping',
        ),
        migrations.AlterField(
            model_name='modalite',
            name='ping',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
