# Generated by Django 5.1.5 on 2025-06-24 22:23

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0043_alter_bdd_options_alter_hard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalModalite_stores',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_modalite', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='imagerie.modalite')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='imagerie.historicalmodalite')),
                ('to_modalite', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='imagerie.modalite')),
            ],
            options={
                'verbose_name': 'HistoricalModalite_stores',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
