# Generated by Django 5.1.5 on 2025-06-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0045_historicalmodalite_printers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodalite',
            name='ping',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
