# Generated by Django 5.2.1 on 2025-06-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0046_historicalmodalite_ping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmodalite',
            name='ping',
        ),
    ]
