# Generated by Django 5.2.3 on 2025-06-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0048_historicalmodalite_eth0_modalite_eth0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmodalite',
            old_name='eth0',
            new_name='macaddr2',
        ),
        migrations.RenameField(
            model_name='modalite',
            old_name='eth0',
            new_name='macaddr2',
        ),
    ]
