# Generated by Django 5.2.3 on 2025-06-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0050_change_model_field_for_macaddr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmodalite',
            name='macaddr',
        ),
        migrations.RemoveField(
            model_name='modalite',
            name='macaddr',
        ),
    ]
