# Generated by Django 5.2.3 on 2025-06-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0051_remove_historicalmodalite_macaddr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmodalite',
            old_name='macaddr2',
            new_name='macaddr',
        ),
        migrations.RenameField(
            model_name='modalite',
            old_name='macaddr2',
            new_name='macaddr',
        ),
    ]
