# Generated by Django 5.2.3 on 2025-10-31 20:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0052_rename_macaddr2_historicalmodalite_macaddr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPresta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('societe', models.CharField(blank=True, max_length=128, null=True)),
                ('acces', models.CharField(blank=True, max_length=128, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical presta',
                'verbose_name_plural': 'historical prestas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Presta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.CharField(blank=True, max_length=128, null=True)),
                ('acces', models.CharField(blank=True, max_length=128, null=True)),
                ('divers', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ManyToManyField(blank=True, help_text=' Contact # ', to='imagerie.contact')),
            ],
            options={
                'db_table': 'Presta',
                'managed': True,
            },
        ),
    ]
