# Generated by Django 5.2.3 on 2025-11-01 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagerie', '0053_historicalpresta_presta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presta',
            name='contact',
        ),
        migrations.RenameField(
            model_name='historicalras',
            old_name='denom',
            new_name='compte',
        ),
        migrations.RenameField(
            model_name='ras',
            old_name='denom',
            new_name='compte',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='societe',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='societe',
        ),
        migrations.RemoveField(
            model_name='historicalras',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='ras',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='compteras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compte_ras', to='imagerie.ras'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='compteras',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='imagerie.ras'),
        ),
        migrations.AddField(
            model_name='historicalras',
            name='societe',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ras',
            name='societe',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalPresta',
        ),
        migrations.DeleteModel(
            name='Presta',
        ),
    ]
